nodeLinker: node-modules

# Ensures deep peer dependencies for Particle/Trezor are hoisted properly
nmHoistingLimits: workspaces

packageExtensions:
  "@solana/wallet-adapter-solflare@*":
    dependencies:
      "@wallet-standard/features": "*"
  "@toruslabs/solana-embed@*":
    dependencies:
      "@babel/runtime": "*"